/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DownloadConfigPanel: typeof import('./src/components/shared/DownloadConfigPanel.vue')['default']
    DownloadingTab: typeof import('./src/components/tasks/DownloadingTab.vue')['default']
    FetchedTab: typeof import('./src/components/tasks/FetchedTab.vue')['default']
    FetchingTab: typeof import('./src/components/tasks/FetchingTab.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    Rating: typeof import('primevue/rating')['default']
    SettingsTab: typeof import('./src/components/tasks/SettingsTab.vue')['default']
    StartFetchTab: typeof import('./src/components/tasks/StartFetchTab.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    WorkspaceGate: typeof import('./src/components/shared/WorkspaceGate.vue')['default']
  }
}
